Add empty directory structure to support later maven builds
googleinterns/step71-2020 pull request #10
Opened 2020-06-24 17:52 UTC by gwynethsc

2020-06-25 03:51 UTC, sperzion commented
I did a bit of Googling, and it appears that the checks don't re-run unless a commit in the PR is changed. So, you can either make a no-op amendment to a commit to make it change, or close this PR and open a new one.

In theory, when the checks run again, it should work (as I followed the instructions for the Build check to connect it to our GCP project).

2020-06-25 22:17 UTC, sperzion requested changes

2020-06-25 22:17 UTC, sperzion commented on project/src/main/java/com/google/sps/data/README
> +This directory is a placeholder for backend Java classes and other data.
Can you please move all the files under ...com/google/sps/ensemble/...? This is to ensure that your namespace does not collide with others also in the com/google/sps namespace.

2020-06-26 17:50 UTC, Google-JM approved these changes
Outside Justin H.'s comments this LGTM.

2020-06-29 19:55 UTC, sperzion approved these changes

2020-06-29 21:20 UTC, merged