Angular workspace doc
googleinterns/step71-2020 pull request #45
Opened 2020-07-10 18:09 UTC by jeward414

2020-07-10 19:54 UTC, sperzion requested changes
Per demo feedback, it's worth revisiting the project creation aspect of workspaces. If you want to continue with this PR as-is, then it's at least worth creating TODOs with tracking issue numbers to indicate what should be revisited.

2020-07-13 17:31 UTC, Google-JM approved these changes
Outside thinking about Justin H.'s comments this looks fine to check in and iterate on.

2020-07-13 18:47 UTC, sperzion approved these changes

2020-07-13 19:33 UTC, gwynethsc approved these changes

2020-07-13 19:37 UTC, merged