Add pom.xml file with basic dependencies that can be modified
googleinterns/step71-2020 pull request #8
Opened 2020-06-24 17:08 UTC by jeward414

Created pom file to run test on local server

2020-06-24 17:28 UTC, jeward414 commented
@googlebot I signed it!

2020-06-24 18:22 UTC, gwynethsc requested changes

2020-06-24 18:22 UTC, gwynethsc commented on project/pom.xml
> +          <deploy.projectId>PROJECTIDHERE</deploy.projectId>
Since the GCP project exists already, I feel like we might as well add the project ID right away so we don't have to worry about it later.

2020-06-24 21:27 UTC, jeward414 commented
@googlebot I fixed it.

2020-06-24 22:49 UTC, gwynethsc approved these changes

2020-06-25 03:48 UTC, sperzion commented
I think this is still stuck on the [one commit](https://github.com/googleinterns/step71-2020/pull/8/commits/5d994876f055808f93cf545a5834c4acb001acec) that's tied to `Jonathan`. You'll either need to start over with a new branch, or delete that commit from the branch history. Here's some info on that: https://githowto.com/removing_commits_from_a_branch

It might be worth it to start over on a new branch, though.

2020-06-25 03:48 UTC, sperzion commented on project/pom.xml
> +          <!-- TODO: set project ID. -->
Can delete this comment.

2020-06-25 15:13 UTC, closed without merging